version: "3.7"
services:
  development:
    hostname: dev
    build:
      context: ./
      dockerfile: development.dockerfile
    volumes:
      - src:/root/src
      - conda_envs:/opt/conda/envs
      - git:/root/.git
volumes:
  src:
  conda_envs:
  git: